import Anthropic from "@anthropic-ai/sdk";

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

const MODEL = process.env.ANTHROPIC_MODEL || "claude-sonnet-4-6";

interface GenerateOpts {
  title: string;
  body: string;
  diff: string;
}

const MAX_DIFF_CHARS = 100_000;

function truncateDiff(diff: string): string {
  if (diff.length <= MAX_DIFF_CHARS) return diff;
  const snippet = diff.slice(0, MAX_DIFF_CHARS);
  const lastNewline = snippet.lastIndexOf("\n");
  return snippet.slice(0, lastNewline) + "\n\n... (diff truncated)";
}

export async function generatePRDescription({
  title,
  body,
  diff,
}: GenerateOpts): Promise<string> {
  const truncatedDiff = truncateDiff(diff);

  const prompt = `You are an expert engineering reviewer. A pull request has been opened. Please write a clear, concise PR description in markdown that summarizes what changed, why it matters, and any risks or follow-ups the reviewer should know.

Original title: ${title}
Original body: ${body || "(empty)"}

Git diff:
\`\`\`diff
${truncatedDiff}
\`\`\`

Respond ONLY with the PR description, no preamble.`;

  const response = await anthropic.messages.create({
    model: MODEL,
    max_tokens: 1024,
    messages: [{ role: "user", content: prompt }],
  });

  const text =
    response.content
      .filter((block): block is { type: "text"; text: string } => block.type === "text")
      .map((block) => block.text)
      .join("\n") || "(GitReview was unable to generate a description.)";

  return `## AI-generated PR description\n\n${text}\n\n---\n_Generated by [GitReview](https://github.com/apps/gitreview)_`;
}
