import { Octokit } from "@octokit/rest";
import { createAppAuth } from "@octokit/auth-app";

const appId = process.env.GITHUB_APP_ID;
const privateKey = process.env.GITHUB_PRIVATE_KEY;
const fallbackToken = process.env.GITHUB_TOKEN;

function getOctokit(installationId?: number): Octokit {
  if (appId && privateKey && installationId) {
    return new Octokit({
      authStrategy: createAppAuth,
      auth: {
        appId,
        privateKey: privateKey.replace(/\\n/g, "\n"),
        installationId,
      },
    });
  }
  if (fallbackToken) {
    return new Octokit({ auth: fallbackToken });
  }
  throw new Error(
    "Missing GitHub credentials. Set GITHUB_APP_ID + GITHUB_PRIVATE_KEY + GITHUB_INSTALLATION_ID, or GITHUB_TOKEN."
  );
}

interface RepoOpts {
  owner: string;
  repo: string;
}

interface PROpts extends RepoOpts {
  pullNumber: number;
  installationId?: number;
}

export async function getPullRequestDiff({
  owner,
  repo,
  pullNumber,
  installationId,
}: PROpts): Promise<string> {
  const octokit = getOctokit(installationId);
  const response = await octokit.rest.pulls.get({
    owner,
    repo,
    pull_number: pullNumber,
    mediaType: {
      format: "diff",
    },
  });
  return response.data as unknown as string;
}

export async function postPRComment({
  owner,
  repo,
  issueNumber,
  body,
  installationId,
}: RepoOpts & { issueNumber: number; body: string; installationId?: number }): Promise<void> {
  const octokit = getOctokit(installationId);
  await octokit.rest.issues.createComment({
    owner,
    repo,
    issue_number: issueNumber,
    body,
  });
}

export async function findExistingBotComment({
  owner,
  repo,
  issueNumber,
  installationId,
  marker = "_Generated by [GitReview]",
}: RepoOpts & { issueNumber: number; installationId?: number; marker?: string }): Promise<number | undefined> {
  const octokit = getOctokit(installationId);
  const { data: comments } = await octokit.rest.issues.listComments({
    owner,
    repo,
    issue_number: issueNumber,
    per_page: 100,
  });
  return comments.find((c) => c.body?.includes(marker))?.id;
}
